version: 2
groups:
  code-review:
    approve_by_comment:
      enabled: true
      approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
      reject_regex: '^(Rejected|:-1:)'
    required: 1
    always_pending:
      title_regex: '(WIP|wip)'
      labels:
        - wip
      explanation: 'This PR is a work in progress...'
    reset_on_push:
      enabled: false
    users:
    - joejordanbrown